var tab_server = ["https://dub01.online.tableau.com/t/eskissite/views/ESG-ESGDashboard/Cockpit","https://dub01.online.tableau.com/t/eskissite/views/ESG-ESGDashboard/Environment","https://dub01.online.tableau.com/t/eskissite/views/ESG-ESGDashboard/CompanyDetail","https://dub01.online.tableau.com/t/eskissite/views/ESG-ESGDashboard/Analysis-Adhoc"];
  var tab_filter=[[],[],[],[]];
  var tab_web=[{"key":"1","val":"true"},{"key":"2","val":"true"},{"key":"0","val":"true"},{"key":"3","val":"true"}];
  var tab_ask=[{"key":"3","val":""},{"key":"0","val":""},{"key":"1","val":""},{"key":"2","val":""}];
  var tab_param=[[],[],[],[]]; 
  var tab_text=[{"key":"Download-Data-text","val":"Download%20Data%20"},{"key":"User-text","val":"Alex"},{"key":"Action-text","val":"Action%20"},{"key":"Terms-text","val":"Terms%20%26%20Conditions%20"},{"key":"Viz-1-text","val":"Cockpit"},{"key":"WebEdit-text","val":"Web%20Edit%20"},{"key":"Viz-4-text","val":"Analysis%20-%20Adhoc"},{"key":"Reset-Viz-text","val":"Reset%20Viz%20"},{"key":"AskData-text","val":"Ask%20data%20"},{"key":"PrivacyPolicy-text","val":"Privacy%20Policy%20"},{"key":"Viz-3-text","val":"Company%20Detail"},{"key":"Viz-2-text","val":"Environment"}];
  var tab_img=[{"key":"img-logo","val":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Logo_acme.svg/2560px-Logo_acme.svg.png"},{"key":"img-avatar","val":"https://assets.webiconspng.com/uploads/2016/12/User-Icon.png"}];
  var tab_action=[{"key":"2","val":"true"},{"key":"1","val":"true"},{"key":"3","val":"true"},{"key":"0","val":"true"}];
  var title_index="ESG_Tableau";